// Original subject explanations; board/session alignment remains provisional.
function T(
  id,
  title,
  category,
  lab,
  concept,
  mechanism,
  problem,
  working,
  code,
  task,
  answer,
  misconception,
  question,
  options,
  correct,
  explanation,
) {
  return {
    id,
    title,
    category,
    lab,
    minutes: 30,
    summary: concept.slice(0, 390),
    objectives: [
      `Explain ${title.toLowerCase()} using a concrete example.`,
      "Trace the mechanism and justify the observed result.",
      "Apply the idea to a changed situation and identify a common mistake.",
    ],
    notes: [
      ["Concept and purpose", concept],
      ["Behind the scenes", mechanism],
      ["A worked investigation", `${problem}\n\n${working}`],
      ["Misconception clinic", misconception],
      ["Transfer the idea", `${task}\n\nCheck your reasoning: ${answer}`],
    ],
    example: {
      title: `Investigating ${title.toLowerCase()}`,
      problem,
      solution: working,
      code,
    },
    practical: {
      task,
      steps: [
        "State the inputs, assumptions and expected result for this investigation.",
        mechanism,
        "Carry out the specific task below and record intermediate observations.",
        task,
      ],
      answer,
    },
    quiz: { question, options, answer: correct, explanation },
  };
}
export const deepLessons = [
  T(
    "hardware-io",
    "Input, output and feedback",
    "Computer systems",
    "cpu",
    "An input device converts an action or measurement into data. An output device presents the result. A feedback system measures the effect of an output and uses that measurement as a later input; input and output are roles in a process, not permanent labels on an entire machine.",
    "In a temperature controller, a sensor measures the room, the program compares the measurement with a target, and a relay controls the fan. The next sensor reading closes the feedback loop. A touchscreen performs both input and output through different components.",
    "A room is at 31°C and the controller turns its fan on above 28°C. What is each stage?",
    "31°C is input data; comparing 31 with 28 is processing; turning on the fan is output. A later reading of 27°C causes the controller to turn the fan off. The program needs a clear boundary rule for exactly 28°C.",
    "temperature = 31\nfan_on = temperature > 28\nprint(fan_on)  # True",
    "Change the reading to 28°C and 27°C. Predict both outputs.",
    "Both comparisons are false because the rule is strictly greater than 28. Document whether the intended design instead uses >=.",
    "A touchscreen is not only an input device: its display is output. A device can participate in multiple stages.",
    "Which reading turns this controller on?",
    ["27°C", "28°C", "29°C"],
    2,
    "Only 29 is strictly greater than the threshold 28.",
  ),
  T(
    "memory-hierarchy",
    "Registers, cache, RAM and storage",
    "Computer systems",
    "cpu",
    "Memory is organised as a hierarchy because speed, capacity, cost and persistence trade off. Registers hold immediate operands; caches retain recently used blocks; RAM holds active programs; secondary storage keeps files. These layers cooperate rather than replace each other.",
    "The processor requests an address. A cache hit supplies the block quickly. On a miss, a slower level supplies it and may populate the cache. Locality explains why nearby or recently used addresses are often requested again. Saving a document makes an explicit persistent copy.",
    "A processor reads the same array repeatedly. Why might later passes be faster?",
    "Recently accessed blocks may remain in cache, reducing slower RAM accesses. A larger array may exceed cache capacity, so the benefit depends on the working set. Cache presence alone does not guarantee a specific time.",
    "Register → L1/L2 cache → RAM → SSD\nFast and small                 Persistent and large",
    "Explain what survives if power is removed after editing a document but before saving.",
    "The saved version on persistent storage may survive; unsaved edits in ordinary RAM are normally lost. Recovery software may help only if it previously wrote a recovery copy.",
    "Cache does not increase the CPU clock frequency. It reduces the average time spent waiting for data.",
    "Which normally retains data without power?",
    ["CPU register", "Ordinary RAM", "SSD"],
    2,
    "An SSD is non-volatile storage; registers and ordinary working RAM are volatile.",
  ),
  T(
    "data-units",
    "Bits, bytes and storage calculations",
    "Data representation",
    "binary",
    "A bit represents one binary choice. Eight bits form a byte. Capacity calculations must keep bits, bytes and prefixes separate: decimal kilo means 1000, while kibi means 1024. A transfer rate in megabits per second cannot be compared directly with a file size in megabytes.",
    "First convert quantities to a common unit. An uncompressed image needs width × height × bits-per-pixel bits, before metadata or row padding. Compression changes the stored size, so the formula is a raw-data estimate.",
    "Estimate the raw storage for a 640 × 480 RGB image with 24 bits per pixel.",
    "There are 307,200 pixels. Multiplying by 24 gives 7,372,800 bits; dividing by 8 gives 921,600 bytes, or 900 KiB. The file on disk may differ because of headers or compression.",
    "640 × 480 × 24 / 8 = 921600 bytes\n921600 / 1024 = 900 KiB",
    "Estimate an uncompressed 100 × 100 image with 8 bits per pixel.",
    "100 × 100 × 8 = 80,000 bits = 10,000 bytes. This is 10 decimal kB, approximately 9.77 KiB.",
    "MB and Mb are different units. A lowercase b commonly denotes bits; an uppercase B denotes bytes.",
    "How many bytes are in 64 bits?",
    ["8", "64", "512"],
    0,
    "Divide the bit count by eight.",
  ),
  T(
    "signed-binary",
    "Signed binary and two’s complement",
    "Data representation",
    "binary",
    "A fixed-width bit pattern has meaning only under an interpretation. In eight-bit unsigned form, 11111111 represents 255. In eight-bit two’s complement, it represents −1. The representable range for n-bit two’s complement is −2^(n−1) through 2^(n−1)−1.",
    "To encode a negative value, write the positive magnitude, invert every bit within the chosen width, and add one. Arithmetic retains the low n bits. Signed overflow and an unsigned carry are related to different interpretations and must not be treated as the same condition.",
    "Encode −5 in eight-bit two’s complement.",
    "+5 is 00000101. Inversion gives 11111010; adding one gives 11111011. The high bit has weight −128, so the value is −128 + 64 + 32 + 16 + 8 + 2 + 1 = −5.",
    "00000101  (+5)\n11111010  (invert)\n11111011  (+1 = −5)",
    "Add 00000101 and 11111011, retaining eight bits.",
    "The nine-bit sum is 100000000. Retaining eight bits gives 00000000, consistent with 5 + (−5) = 0.",
    "The leading bit in two’s complement is not an independent sign followed by a magnitude. All bits participate in the positional value.",
    "What is the eight-bit signed range?",
    ["0 to 255", "−127 to 128", "−128 to 127"],
    2,
    "Eight-bit two’s complement has 256 values, from −128 to 127.",
  ),
  T(
    "unicode-encoding",
    "Characters, Unicode and UTF-8",
    "Data representation",
    "journey-file",
    "Unicode assigns code points to characters. UTF-8 is one encoding that turns those code points into bytes. The number of characters, code points and bytes can differ; a visible character may also contain multiple code points. This matters when storing Indian-language text.",
    "A program encodes a string before writing bytes and decodes bytes after reading them. Both operations must agree on the encoding. ASCII characters use one UTF-8 byte; many other characters use several. Incorrect decoding can produce errors or replacement symbols.",
    "Why can two strings with the same number of letters have different file sizes?",
    "Their code points can require different numbers of UTF-8 bytes. For example A uses one byte while the check mark ✓ uses three. Size limits should specify whether they count bytes, code points or displayed characters.",
    'text = "A✓"\nprint(len(text))  # 2 code points\nprint(len(text.encode("utf-8")))  # 4 bytes',
    "Encode the string A✓, then decode the bytes using UTF-8.",
    "The round trip reproduces A✓. The byte sequence in hexadecimal is 41 E2 9C 93.",
    "Unicode and UTF-8 are not synonyms: Unicode defines characters and code points; UTF-8 defines an encoding.",
    "Which converts a Python string to UTF-8 bytes?",
    ['text.encode("utf-8")', "text.upper()", "len(text)"],
    0,
    "encode creates a byte representation using the selected encoding.",
  ),
  T(
    "boot-process",
    "From power-on to the operating system",
    "Operating systems",
    "cpu",
    "Booting is the sequence that prepares hardware and loads an operating system. Firmware begins before the operating system exists in RAM. It identifies a boot target, and a boot loader arranges for a kernel to run. Exact details vary across devices and firmware designs.",
    "A typical sequence is power-on, firmware checks, boot-device selection, boot-loader execution, kernel initialisation, services, then a login or desktop. A failure at an early stage prevents later stages from appearing. Diagnostic observations should identify the last completed stage.",
    "A computer displays firmware settings but never reaches the OS login screen. Is the display necessarily broken?",
    "No. Showing firmware output proves at least part of the display path works. The next investigation concerns boot-device detection, boot order, boot-loader configuration or OS startup. A failed login is a different, later-stage problem.",
    "Power → Firmware → Boot loader → Kernel → Services → Login",
    "Draw the sequence and mark where a missing boot drive would first be detected.",
    "It is usually identified during firmware device discovery or when the loader tries to access its boot files, depending on the platform. No user application can start normally before the kernel is running.",
    "Restarting an application is not the same as rebooting the machine: the OS remains running during an application restart.",
    "Which normally starts first?",
    ["Spreadsheet application", "Firmware", "Login session"],
    1,
    "Firmware executes before loading the operating system.",
  ),
  T(
    "process-states",
    "Processes, threads and state changes",
    "Operating systems",
    "cpu",
    "A program is stored instructions; a process is an executing instance with state and resources. A process may contain multiple threads that share parts of its address space. Running, ready and blocked describe whether execution currently has CPU time or is waiting.",
    "A ready task can run when scheduled. A blocked task waits for an event such as I/O completion and cannot use CPU time productively for that operation. When the event occurs, it becomes ready again. A context switch saves one execution state and restores another.",
    "A music player requests a file block that has not arrived from storage. What happens?",
    "The requesting thread can block while another ready task uses the CPU. When the data arrives, the waiting thread becomes ready; it may still wait for scheduling before running again. Ready does not mean currently running.",
    "Ready → Running → Blocked\n          ↓          ↓ I/O complete\n        Ready ←──── Ready",
    "Classify a task waiting for keyboard input and a task waiting only for CPU time.",
    "The keyboard-waiting task is blocked on an event. The task waiting only for CPU time is ready.",
    "A process shown in a task manager is not necessarily executing on a CPU at that instant.",
    "An I/O completion usually moves a blocked task into which state?",
    ["Ready", "Terminated", "Always immediately running"],
    0,
    "The task becomes eligible to run; the scheduler determines when it gets CPU time.",
  ),
  T(
    "cpu-scheduling",
    "CPU scheduling with a timeline",
    "Operating systems",
    "cpu",
    "A scheduler chooses among ready tasks. Different policies optimise different goals such as response time, throughput and fairness. Waiting time counts time spent ready but not running; turnaround time measures completion time minus arrival time. State all assumptions before comparing algorithms.",
    "For non-preemptive first-come, first-served scheduling, tasks run in arrival order until they finish or block. In round robin, a time quantum limits how long one ready task runs before another gets a turn. Context-switch cost affects real performance.",
    "Three tasks arrive at time 0 in order A, B, C with CPU bursts 4, 2 and 3 ms. Find FCFS waiting times.",
    "A runs 0–4, B runs 4–6, C runs 6–9. Their waiting times are 0, 4 and 6 ms. Average waiting time is (0+4+6)/3 = 10/3 ms. No I/O or switching cost is assumed.",
    "0 ── A ── 4 ─ B ─ 6 ── C ── 9\nWaiting: A=0, B=4, C=6",
    "Reorder the same arrivals as B, C, A and calculate the new average waiting time.",
    "Waiting times become B=0, C=2, A=5; the average is 7/3 ms. Changing arrival order changes FCFS results.",
    "Turnaround time includes execution time; waiting time does not. They are equal only in special cases.",
    "For the original order, when does task C finish?",
    ["6 ms", "9 ms", "3 ms"],
    1,
    "C begins at 6 ms and needs 3 ms of CPU time.",
  ),
  T(
    "virtual-memory",
    "Paging and virtual addresses",
    "Operating systems",
    "cpu",
    "Virtual memory gives a process an address space whose addresses are translated to physical memory. Paging divides that address space into equal-sized pages and physical memory into frames. A page table records mappings and access permissions. Virtual memory is more than a synonym for a disk swap file.",
    "Split an address into page number and offset. Use the page number to find its frame, then combine the frame number with the unchanged offset. A page fault occurs when the access cannot be completed using the current mapping, and the OS must handle it.",
    "With a page size of 1024 bytes, translate virtual address 2500 when virtual page 2 maps to frame 7.",
    "2500 = 2×1024 + 452, so the page is 2 and the offset is 452. The physical address is 7×1024 + 452 = 7620. This example assumes the entry is present and permits the access.",
    "page = 2500 // 1024  # 2\noffset = 2500 % 1024  # 452\nphysical = 7 * 1024 + offset  # 7620",
    "Translate address 1100 if page 1 maps to frame 4 and page size remains 1024.",
    "The offset is 76, giving physical address 4×1024 + 76 = 4172.",
    "A page number can change during translation; the within-page offset does not change in basic paging.",
    "Which part is unchanged by this translation?",
    ["Page number", "Frame number", "Offset"],
    2,
    "The offset identifies the same position within the selected frame.",
  ),
  T(
    "file-systems",
    "Files, directories and paths",
    "Operating systems",
    "journey-file",
    "A filesystem organises persistent data and metadata. A file name identifies a directory entry; a path explains how to reach it. Absolute paths start from a root, while relative paths depend on a current directory. File extensions are naming conventions, not proof of content type.",
    "To open a path, the system resolves directory components, checks permissions, locates metadata and then reads or writes data blocks. The same relative path can refer to different files when the working directory changes. A rename changes a name, not automatically the file format.",
    "A project contains notes/chapter1.txt. Why might opening chapter1.txt fail?",
    "If the working directory is the project root, the file is inside notes and its relative path is notes/chapter1.txt. Opening only chapter1.txt looks in the current directory. The failure should be diagnosed before creating a duplicate file.",
    "project/\n  notes/\n    chapter1.txt\nRelative from project: notes/chapter1.txt",
    "State the relative path to images/gates.png from the project root.",
    "Use images/gates.png. From inside the notes directory, a typical relative path is ../images/gates.png.",
    "Renaming picture.jpg to picture.pdf does not convert an image into a PDF.",
    "A relative path is interpreted from what location?",
    [
      "Always the disk root",
      "The current working directory",
      "Always the user’s desktop",
    ],
    1,
    "Its meaning depends on the working directory.",
  ),
  T(
    "permissions",
    "Accounts, permissions and least privilege",
    "Operating systems",
    "journey-file",
    "Permissions control which operations an account can perform. Authentication establishes an identity; authorisation decides what that identity may do. Least privilege means granting only the access necessary for a task and reviewing it when responsibilities change.",
    "A teacher account may publish notes, while a student account may read published notes. The server must enforce these rules for each request. Hiding a button in the interface improves usability but cannot substitute for an access check on the protected operation.",
    "A student edits a web request to call a teacher-only publishing endpoint. What must stop it?",
    "The backend must reject the request when the session lacks teacher privileges. The interface is not a trusted enforcement boundary because a user can construct requests without using its buttons.",
    "Identity → Session → Permission check → Allowed operation\n                                    ↘ Denial",
    "Design three permissions for a school notes portal.",
    "Students: read published material. Teachers: create private drafts and publish assigned material. Administrators: manage teacher access. Avoid giving student accounts administrative permissions.",
    "A password does not automatically grant permission to every resource; it only helps establish the account identity.",
    "What is authorisation?",
    [
      "Checking what an identity is allowed to do",
      "Drawing a login page",
      "Compressing a password",
    ],
    0,
    "Authorisation checks permitted actions and resources.",
  ),
  T(
    "deadlocks",
    "Deadlock and safe resource ordering",
    "Operating systems",
    "cpu",
    "A deadlock is a situation in which tasks wait for resources held by one another and none can proceed. A classic resource model identifies mutual exclusion, hold-and-wait, no forced preemption and circular wait as necessary conditions. A slow task is not automatically deadlocked.",
    "Imagine task A holding the printer lock while requesting the scanner lock, and task B holding the scanner lock while requesting the printer lock. Consistent acquisition order removes this particular circular wait: both tasks request resources in the same global order.",
    "Explain the wait-for cycle for tasks A and B.",
    "A waits for B to release the scanner; B waits for A to release the printer. Neither voluntarily releases its held lock while waiting. The dependency graph contains A→B→A, indicating the cycle in this simple example.",
    "A holds printer → waits scanner\nB holds scanner → waits printer",
    "Choose a lock order that prevents this cycle.",
    "Require both tasks to acquire printer before scanner and release them after use. A task must not hold scanner while trying to acquire printer under this rule.",
    "Deadlock, starvation and long processing time are different problems; identify what each task is waiting for.",
    "Which design breaks the example’s circular wait?",
    [
      "Different lock orders for each task",
      "One consistent lock order",
      "Increasing the display resolution",
    ],
    1,
    "A global resource order prevents a cycle of incompatible acquisition orders.",
  ),
  T(
    "os-services",
    "Operating-system services and system calls",
    "Operating systems",
    "cpu",
    "The OS manages resources and provides controlled services to programs. Applications request operations such as reading files, creating processes and communicating through system interfaces. Protection separates ordinary application code from privileged operations that could affect the whole machine.",
    "An application calls a library routine; the library may make a system call; the kernel checks the request and interacts with a device driver. The result or an error returns through the interface. Not every library function needs a system call.",
    "Trace a program reading bytes from a file.",
    "The program requests a read. The OS checks the handle and permissions, locates the data, and copies or maps the result as appropriate. The call reports how many bytes were read or an error; the application must handle that result.",
    "Application → Library → System call → Kernel → Driver",
    "Explain why an application should handle a failed read.",
    "A file may be missing, access may be denied, or an I/O error may occur. The application must report or recover from the actual error rather than treating missing bytes as valid data.",
    "A graphical desktop is one interface to an OS, not the entire OS.",
    "Which component normally enforces protected hardware access?",
    ["Kernel", "Document title", "Webpage colour theme"],
    0,
    "The kernel provides controlled access to privileged resources.",
  ),
  T(
    "backup-recovery",
    "Backups, versions and recovery",
    "Digital skills",
    "journey-file",
    "A backup is a separate recoverable copy, not merely another shortcut to the same file. Recovery plans must consider accidental deletion, corruption and loss of the original device. Version history helps recover earlier states, while synchronisation alone can propagate a deletion.",
    "Choose what to protect, schedule copies to independent destinations, restrict access and test restoration. A practical school workflow keeps a working file, a local backup and an appropriately protected off-device copy. Retention rules determine which older versions survive.",
    "A synchronised folder deletes a document on both the laptop and cloud. Why did synchronisation not guarantee recovery?",
    "Sync replicated the deletion. Recovery depends on separate version history, recycle-bin retention or a backup. Test restoration before relying on a service for important teaching material.",
    "Working copy → Versioned backup → Restore test\n                       ↘ Separate location",
    "Design a weekly recovery test for your practical journal.",
    "Restore a selected backup into a new folder, open it, compare its content with the expected version and record the result. Do not overwrite the working copy during the test.",
    "A backup that has never been restored successfully is an untested recovery assumption.",
    "Which is the strongest evidence that a backup is usable?",
    [
      "Its filename says backup",
      "It restores the expected content",
      "It shares the same folder icon",
    ],
    1,
    "A restoration check verifies that the saved data can actually be recovered.",
  ),
  T(
    "boolean-laws",
    "Boolean laws and De Morgan’s theorem",
    "Digital electronics",
    "gates",
    "Boolean algebra models values 0 and 1 using operations such as AND, OR and NOT. Algebraic laws let us transform an expression without changing its truth table. In Boolean notation, multiplication often means AND and addition often means OR, not ordinary arithmetic.",
    "De Morgan’s laws state NOT(A AND B) = NOT A OR NOT B, and NOT(A OR B) = NOT A AND NOT B. Complement every input and exchange AND with OR when moving a NOT across a grouped expression. Check equivalence for every input row.",
    "Show that NOT(A AND B) equals NOT A OR NOT B for A=1, B=0.",
    "A AND B is 0, so its complement is 1. NOT A is 0 and NOT B is 1; their OR is 1. Matching this row alone is not a full proof, so repeat for 00, 10 and 11.",
    "A B | NOT(A AND B) | NOT A OR NOT B\n0 0 | 1 | 1\n0 1 | 1 | 1\n1 0 | 1 | 1\n1 1 | 0 | 0",
    "Simplify A OR (A AND B).",
    "The absorption law gives A. If A=1, the expression is 1 regardless of B; if A=0, both terms are 0.",
    "Boolean 1 OR 1 equals 1, not the arithmetic sum 2.",
    "What is NOT(A OR B) equivalent to?",
    ["NOT A OR NOT B", "NOT A AND NOT B", "A AND B"],
    1,
    "De Morgan’s law exchanges OR with AND and complements both inputs.",
  ),
  T(
    "multiplexer",
    "Multiplexers and selected data paths",
    "Digital electronics",
    "journey-circuit",
    "A multiplexer selects one of several data inputs and forwards it to an output. A 2-to-1 multiplexer needs one select bit. Selection is useful when multiple possible sources share a destination, such as operands entering a processor’s arithmetic unit.",
    "For select S, Y = (NOT S AND D0) OR (S AND D1). When S=0, only D0 can reach the OR gate; when S=1, only D1 can. The selection logic gates the data rather than adding the values together.",
    "With D0=1 and D1=0, find Y for both values of S.",
    "For S=0, Y=1. For S=1, Y=0. Changing S redirects the data path even though neither data input changes. A four-input multiplexer generally needs two select bits.",
    "S D0 D1 | Y\n0  1  0 | 1\n1  1  0 | 0",
    "Set D0=D1=1 and vary S. Explain the result.",
    "Y remains 1 because both possible selected inputs are 1. Selection still occurs, but the values make the result indistinguishable.",
    "A multiplexer is not a storage element: its output is determined by current inputs and select signals in this combinational model.",
    "How many select bits choose one of four inputs?",
    ["1", "2", "4"],
    1,
    "Two binary select bits represent four possible choices.",
  ),
  T(
    "decoder",
    "Decoders and one-of-many selection",
    "Digital electronics",
    "gates",
    "A decoder converts an encoded input into an active output line. In an ideal active-high 2-to-4 decoder, each two-bit input selects exactly one of four outputs when enabled. Real devices may use active-low outputs or additional enable pins, so read the chosen device’s datasheet.",
    "Form one minterm for each input combination. For inputs A and B: Y0=NOT A AND NOT B, Y1=NOT A AND B, Y2=A AND NOT B, and Y3=A AND B. Only the expression matching the current input is true.",
    "Which line is selected when A=1 and B=0?",
    "Y2 is 1 in the active-high enabled model; Y0, Y1 and Y3 are 0. This is a one-hot representation of the input value 2.",
    "AB | Y0 Y1 Y2 Y3\n00 | 1  0  0  0\n01 | 0  1  0  0\n10 | 0  0  1  0\n11 | 0  0  0  1",
    "Draw a truth table for an enabled 1-to-2 active-high decoder.",
    "For input 0, outputs are Y0=1,Y1=0. For input 1, outputs are Y0=0,Y1=1. Specify a disabled state separately if an enable input is added.",
    "The number printed on an IC does not tell you its signal polarity. An active-low selected output is 0, not 1.",
    "In the stated model, input 11 activates which output?",
    ["Y0", "Y2", "Y3"],
    2,
    "Binary 11 selects output number 3.",
  ),
  T(
    "cpu-buses",
    "Address, data and control buses",
    "Processor organisation",
    "journey-cpu",
    "A bus carries information between components. An address identifies a location, data carries the value being transferred, and control signals describe actions such as read or write. Bus width and addressable unit together determine what an address can identify.",
    "In a simplified memory read, the processor places an address on the address path, asserts read control and receives the selected value on the data path. A write provides both an address and a value with write control. Timing and multiplexing vary by processor.",
    "How much byte-addressable memory can a 16-bit address identify?",
    "Sixteen address bits represent 2^16 = 65,536 distinct addresses. If each address selects one byte, the address space is 65,536 bytes or 64 KiB. An eight-bit data bus does not reduce the number of addresses.",
    "Address: 2500H → Memory location\nControl: READ\nData: value at 2500H → CPU",
    "Compare an 8-bit data bus with a 16-bit address bus.",
    "The data width describes the size of a basic parallel transfer; the address width describes the number of distinct addresses. They measure different properties.",
    "The 8085 multiplexes low address and data signals on shared pins; the conceptual bus roles remain distinct.",
    "A 16-bit byte address space contains how many addresses?",
    ["16", "256", "65,536"],
    2,
    "There are 2^16 possible address patterns.",
  ),
  T(
    "8085-architecture",
    "8085 architecture and register roles",
    "Processor organisation",
    "journey-cpu",
    "The 8085 is an eight-bit microprocessor with an accumulator, general-purpose registers, flags, a program counter and a stack pointer. Register roles matter when reading assembly: instructions describe transfers and operations on these named storage locations. The model is historical and educational.",
    "A commonly taught view includes registers B,C,D,E,H,L and accumulator A. Register pairs can support sixteen-bit operations. The program counter identifies the next instruction address; the stack pointer tracks the stack location. Fetch, decode and execute coordinate these parts.",
    "After MVI A,2AH followed by MOV B,A, what do A and B contain?",
    "A contains 2AH after the first instruction. MOV copies that value into B, so both registers contain 2AH. Copying a register value does not erase the source.",
    "MVI A, 2AH\nMOV B, A\nHLT\n; A = 2AH, B = 2AH",
    "Explain the difference between the program counter and the accumulator.",
    "The program counter tracks instruction addresses; the accumulator holds an operand or result for many arithmetic and logic operations. They cannot be substituted without changing the instruction’s meaning.",
    "The program counter does not directly count the number of source-code lines. Instructions can have different byte lengths.",
    "Which register is the accumulator?",
    ["A", "PC", "SP"],
    0,
    "The accumulator is register A.",
  ),
  T(
    "8085-addressing",
    "8085 addressing modes",
    "Processor organisation",
    "journey-cpu",
    "An addressing mode explains where an instruction obtains its operand. Immediate data is included in the instruction; register addressing names a register; direct addressing supplies a memory address; register-indirect addressing uses a register pair to identify a location.",
    "MVI A,2AH places the literal byte 2AH in A. LDA 2500H loads the byte stored at address 2500H. MOV A,M uses the HL pair as a memory pointer in 8085 notation. The same numeric text can mean a value or an address depending on the instruction.",
    "Contrast MVI A,25H with LDA 0025H.",
    "The first loads the literal value 25H into A. The second reads memory location 0025H and loads whatever byte is stored there. Without knowing that memory value, you cannot predict A for the second case.",
    "MVI A, 25H ; immediate byte\nLDA 0025H  ; value stored at address 0025H\nMOV A, M   ; memory location addressed by HL",
    "If HL=2500H and memory[2500H]=7BH, predict MOV A,M.",
    "A becomes 7BH. The HL address selects the source memory location; it does not become the eight-bit accumulator value.",
    "An address is not the same thing as the data stored at that address.",
    "What does M represent in MOV A,M?",
    ["A literal letter", "Memory addressed through HL", "Always address 0000H"],
    1,
    "M is the 8085 notation for the memory location pointed to by HL.",
  ),
  T(
    "8085-flags",
    "8085 arithmetic and status flags",
    "Processor organisation",
    "journey-cpu",
    "Status flags record properties of certain operation results. In the 8085, common flags include carry, zero, sign, parity and auxiliary carry. Each instruction’s flag effects must be checked; not every instruction changes every flag.",
    "For eight-bit addition, keep the low eight result bits in A. Carry records a ninth-bit carry. Zero is set when the stored result is zero. Sign follows bit 7. Parity is set for an even number of one bits in the result; auxiliary carry concerns carry from bit 3 to bit 4.",
    "Find the accumulator and carry for FFH + 01H.",
    "The mathematical sum is 100H. A stores 00H and carry becomes 1. Zero becomes 1, sign becomes 0, and parity is even because zero has zero one bits. Auxiliary carry is also 1 for this addition.",
    "MVI A, FFH\nMVI B, 01H\nADD B\n; A=00H CY=1 Z=1 S=0 P=1 AC=1",
    "Calculate A and carry for 7FH + 01H.",
    "A becomes 80H and carry is 0. If the operands are interpreted as signed two’s complement, 127 + 1 is outside the signed eight-bit range; the unsigned carry alone does not identify signed overflow.",
    "Parity counts set bits, not whether the numeric value is an even integer.",
    "Is the number of one bits in 03H even?",
    ["Yes: two one bits", "No: three one bits", "Parity is undefined"],
    0,
    "03H is 00000011, which has two set bits.",
  ),
  T(
    "8085-stack",
    "8085 stack, calls and returns",
    "Processor organisation",
    "journey-cpu",
    "A stack follows last-in, first-out order. The 8085 uses the stack for operations such as saving register pairs and storing return addresses during subroutine calls. A valid stack pointer and reserved stack memory are prerequisites for reliable stack operations.",
    "In the standard 8085 model, the stack grows toward lower memory addresses. PUSH adjusts SP and stores bytes; POP retrieves them and adjusts SP in the opposite direction. CALL saves a return address before transferring control; RET restores the saved return address.",
    "A subroutine changes B and C but its caller needs their old values. What pattern helps?",
    "Save the BC pair before changing it, perform the subroutine work, and restore the pair before returning. Every saved value must be restored in reverse order. The subroutine must also preserve the call’s return-address discipline.",
    "; SP must already be initialised\nPUSH B\n; subroutine work using B and C\nPOP B\nRET",
    "Explain why PUSH B followed by PUSH D must be restored as POP D then POP B.",
    "The DE pair was saved last and sits on top of the stack. Reversing that order restores each saved pair to its intended destination.",
    "A stack is not unlimited. Overwriting adjacent memory through incorrect SP management can corrupt data or return addresses.",
    "Which saved pair is popped first?",
    ["The first saved", "The most recently saved", "Always HL"],
    1,
    "The stack uses last-in, first-out order.",
  ),
  T(
    "8085-branch",
    "8085 comparisons and conditional branches",
    "Processor organisation",
    "journey-cpu",
    "Conditional branches use flag state to decide whether execution continues sequentially or jumps to another address. A comparison may set flags as if subtraction had occurred while leaving the compared accumulator value unchanged. Instruction-specific behaviour matters when predicting a branch.",
    "CMP B compares A with B. In a simple unsigned comparison, the zero flag indicates equality and carry indicates A is less than B. A following JZ or JC examines that flag state. An intervening flag-changing instruction can invalidate the intended test.",
    "With A=05H and B=05H, what happens after CMP B followed by JZ EQUAL?",
    "The comparison yields a zero difference, so Z is set and JZ transfers control to EQUAL. A remains 05H. The jump relies on the comparison’s flags still being current.",
    "MVI A, 05H\nMVI B, 05H\nCMP B\nJZ EQUAL\n; non-equal path\nEQUAL: HLT",
    "Predict the equality branch when B changes to 06H.",
    "A and B are no longer equal, so Z is 0 and JZ does not take the equality branch. Under unsigned comparison, carry is set because A is less than B.",
    "CMP is not the same as storing a subtraction result in A; it preserves A while setting comparison flags.",
    "Which flag is tested by JZ?",
    ["Carry", "Zero", "Sign"],
    1,
    "JZ branches when the zero flag is set.",
  ),
  T(
    "interrupts",
    "Interrupts and responding to events",
    "Processor organisation",
    "cpu",
    "An interrupt requests attention from the processor so that an event can be handled without continuously checking it in a tight polling loop. The processor transfers control to an interrupt service routine according to its architecture and current interrupt settings.",
    "A simplified sequence is event, interrupt request, acceptance at an appropriate boundary, saving the necessary execution context, service routine, and return. The service routine must preserve required state and avoid assuming it can ignore other timing constraints.",
    "Why might an input device use an interrupt rather than constant polling?",
    "The CPU can perform other work between events. When input arrives, the device requests service. Polling is simpler in some designs but can waste time or miss timing requirements if the polling interval is poorly chosen.",
    "Device event → Interrupt request → Service routine → Resume",
    "Compare polling a keyboard every second with receiving an event notification.",
    "Polling may introduce up to about one polling interval of detection delay under the stated model. Event notification can respond promptly when serviced, although real latency depends on hardware and scheduling.",
    "An interrupt is not a guarantee of immediate execution with zero delay. Priorities, masking and the current instruction affect response.",
    "What is the purpose of an interrupt service routine?",
    [
      "To handle the event",
      "To erase all application state",
      "To permanently stop the CPU",
    ],
    0,
    "It performs the work needed to service the interrupt and allows execution to continue appropriately.",
  ),
  T(
    "network-layers",
    "Layers and encapsulation",
    "Computer networks",
    "journey-web",
    "Layering separates networking responsibilities so that applications need not implement every detail of physical transmission. Encapsulation adds control information around data as it passes through a protocol stack. Different teaching models group these responsibilities into different numbers of layers.",
    "A web message can be carried by a transport connection, placed into IP packets and sent over link-layer frames. At the receiver, headers are interpreted at their corresponding layers. Each layer has a distinct job; an IP address and a link-layer address are not interchangeable.",
    "Trace a browser’s request over a typical TCP/IP path.",
    "HTTP describes the application message. TCP supplies a reliable ordered byte stream for this example. IP supports addressing and routing across networks. A local link technology such as Ethernet or Wi-Fi carries the next-hop frame. Modern web traffic can also use other transports, such as QUIC.",
    "HTTP message → TCP segment → IP packet → Link frame",
    "State what changes when a packet crosses from Wi-Fi to a wired link.",
    "The local link framing changes. The communication still follows network-layer routing, with relevant packet fields such as hop limit changing as specified. Application meaning does not depend on every hop using the same link technology.",
    "The OSI reference model and the practical TCP/IP stack are related models, not identical lists of protocols.",
    "Which layer’s role includes routing IP packets?",
    [
      "Network / Internet layer",
      "Application formatting only",
      "Keyboard input layer",
    ],
    0,
    "Routing across networks is a network-layer function.",
  ),
  T(
    "dns",
    "DNS names and address resolution",
    "Computer networks",
    "journey-web",
    "DNS is a distributed naming system. A browser often needs an address associated with a host name before contacting its server. DNS records have types and lifetimes; a domain name is not itself an IP address, and a name can have several relevant records.",
    "A client asks a resolver, which may answer from cache or consult other DNS servers. Record caching reduces repeated work but means changes can take time to become visible while older cached entries remain valid. A failed lookup can stop a connection before the target web server is contacted.",
    "The browser cannot resolve classroom.example. Should you first debug the server’s page styling?",
    "No. The failure occurs before a successful server connection in this scenario. Check the name, resolver response and network configuration. Styling can only affect a page after content is obtained or already cached locally.",
    "Host name → Resolver → DNS answer → Server address",
    "Explain why a recently changed DNS record may appear differently on two devices.",
    "Their resolvers or local caches may hold different valid cached data. Cache expiration, resolver choice and configuration should be checked before assuming the authoritative change failed.",
    "DNS lookup is not the same as downloading a webpage. It resolves names and other record data.",
    "What does an A record contain?",
    ["An IPv4 address", "A complete HTML page", "A password"],
    0,
    "An A record maps a name to an IPv4 address.",
  ),
  T(
    "tcp-udp",
    "TCP, UDP and transport trade-offs",
    "Computer networks",
    "journey-web",
    "Transport protocols deliver data between application endpoints. TCP presents a reliable ordered byte stream with flow and congestion control. UDP provides datagrams without those guarantees at the UDP layer. Applications may add reliability or other features above UDP when needed.",
    "A TCP connection tracks byte order, acknowledgements and retransmissions. A UDP receiver gets available datagrams independently; missing, duplicated or reordered datagrams are possibilities that the application must handle if they matter. Protocol choice depends on the application’s requirements.",
    "Why might a live voice system tolerate losing a small late packet instead of waiting indefinitely?",
    "For real-time conversation, delayed audio may be less useful than continuing with the current audio. This does not mean all UDP traffic is automatically fast or all real-time protocols ignore loss; the application’s design determines the trade-off.",
    "TCP: ordered byte stream + recovery\nUDP: individual datagrams; application decides extra guarantees",
    "Choose a suitable transport property for a file transfer whose bytes must arrive correctly.",
    "Reliable delivery and ordering are needed somewhere in the system. TCP supplies them as a stream, while a UDP-based application would need to implement appropriate reliability mechanisms itself.",
    "UDP is not a synonym for unreliable application design: applications can build reliable protocols above it.",
    "Which property does TCP provide to applications?",
    [
      "Guaranteed zero latency",
      "An ordered byte stream",
      "Unlimited bandwidth",
    ],
    1,
    "TCP provides a reliable ordered byte-stream abstraction, not zero delay or unlimited capacity.",
  ),
  T(
    "http-tls",
    "HTTP requests and HTTPS protection",
    "Computer networks",
    "journey-web",
    "HTTP describes requests and responses such as GET /notes and a status code. HTTPS carries HTTP through a protected connection, typically using TLS. Encryption protects data in transit, while server identity checks help the browser determine which endpoint it is communicating with.",
    "The browser establishes the appropriate secure connection, validates the server certificate according to its trust rules, and exchanges HTTP messages. The server still needs authentication, authorisation and validation for its application. Transport protection does not repair incorrect application logic.",
    "A site uses HTTPS but lets any signed-in student publish teacher notes. Is the permission problem solved by encryption?",
    "No. HTTPS protects the communication channel; the server must separately check publishing permissions. Encrypted delivery of an unauthorised action is still an authorisation failure.",
    "GET /notes → HTTP request\n200 OK → successful response\nTLS → protected communication channel",
    "Explain the difference between HTTP status 404 and a DNS-resolution error.",
    "A 404 is an HTTP response saying the requested resource was not found by a contacted HTTP server. A DNS-resolution error can prevent that server connection from being established at all.",
    "A padlock does not certify that a website’s content is honest or that its application has no bugs.",
    "Which layer of protection does HTTPS primarily provide?",
    [
      "Transport protection and endpoint identity checks",
      "Automatic correctness of every program",
      "Automatic permission to publish",
    ],
    0,
    "TLS protects the channel and supports server authentication; application checks remain necessary.",
  ),
  T(
    "network-devices",
    "Switches, routers and access points",
    "Computer networks",
    "journey-web",
    "Network devices have different forwarding roles. An Ethernet switch forwards frames within a local network using learned link-layer addresses. A router forwards packets between IP networks. A wireless access point connects wireless clients to a local network; a home appliance may combine several roles.",
    "A host determines whether a destination is local under its addressing configuration. For a remote network, it sends traffic toward a gateway. The gateway chooses a next hop. Each link has its own frame delivery, while routing moves the communication toward the destination network.",
    "Why is a home “Wi-Fi router” more than one conceptual device?",
    "It often combines a router, Ethernet switch, wireless access point and other services. Calling the entire box a router is convenient, but separating its roles makes troubleshooting more precise.",
    "Laptop → Access point → Router → Other network",
    "A printer and laptop are on the same local network. Does every local transfer necessarily cross the internet?",
    "No. Local network communication can remain within the local network. Whether a particular printing service uses cloud features is a separate application choice.",
    "A switch and a router are not identical devices just because both can have Ethernet ports.",
    "Which role forwards packets between IP networks?",
    ["Router", "Text editor", "Display panel"],
    0,
    "A router selects paths between networks.",
  ),
  T(
    "network-topologies",
    "Topologies, reliability and bottlenecks",
    "Computer networks",
    "network",
    "A topology describes how nodes and links are arranged. Physical topology concerns actual connections; logical topology concerns communication relationships. Star, bus, ring and mesh models help compare cost, failure behaviour and manageability, but real deployments may combine them.",
    "In a star model, each endpoint connects to a central device. Failure of one endpoint link can isolate that endpoint, while failure of the central device can affect many endpoints. A mesh offers alternate paths at the cost of more links and more complex management.",
    "A classroom has twelve PCs connected to one switch. Which failure has a broader direct impact: one PC cable or the switch?",
    "A failed PC cable usually disconnects that PC. A failed central switch can disconnect every PC relying on it. Redundant design can reduce this dependency, but redundancy must be deliberately planned and tested.",
    "PC1 ─┐\nPC2 ─┼─ Switch ─ Router\nPC3 ─┘",
    "For four fully interconnected nodes, calculate the number of undirected links.",
    "Each node connects to three others, but counting from both ends doubles the total: 4×3/2 = 6 links.",
    "A visually neat diagram does not prove fault tolerance. Identify which component failures break each communication path.",
    "How many links connect four nodes in a full undirected mesh?",
    ["4", "6", "12"],
    1,
    "Use n(n−1)/2, giving 6.",
  ),
  T(
    "dhcp",
    "DHCP and automatic host configuration",
    "Computer networks",
    "address",
    "A host needs compatible network configuration to communicate. DHCP can supply an address lease and other settings such as a default gateway and DNS servers. An address lease is time-limited and managed; it is not a permanent ownership claim over an address.",
    "In a commonly taught IPv4 exchange, the client discovers servers, receives an offer, requests a configuration and receives an acknowledgement. The exact message flow depends on the client’s state. A working Wi-Fi connection does not by itself prove that IP configuration succeeded.",
    "A laptop associates with Wi-Fi but receives no usable IP configuration. What should be investigated?",
    "Check DHCP reachability, available leases and client configuration. Link association and network-layer configuration are different stages. A device can show a wireless connection while still being unable to reach its gateway.",
    "Discover → Offer → Request → Acknowledge\nLease: address + lifetime + configuration",
    "Explain why the default gateway and DNS server are separate settings.",
    "The gateway routes traffic to other networks. The DNS server resolves names and related records. One address may provide multiple services, but the roles remain distinct.",
    "An automatically assigned address does not guarantee internet access; routing, name resolution and upstream connectivity must also work.",
    "What does DHCP commonly provide?",
    [
      "An IP address lease and configuration",
      "The content of every website",
      "A compiler",
    ],
    0,
    "DHCP automates host configuration such as address leases and related options.",
  ),
  T(
    "html-semantics",
    "Semantic HTML and accessible structure",
    "Web development",
    "journey-web",
    "Semantic HTML describes the meaning of content, not only its visual appearance. Headings, navigation, main content, articles and buttons give browsers and assistive technologies a useful structure. A large bold paragraph does not become a heading merely because it looks like one.",
    "Choose elements according to purpose: links navigate, buttons perform actions, labels identify form controls, and headings establish a hierarchy. CSS can change appearance while preserving meaning. Keyboard access should be checked along with pointer interaction.",
    "A clickable div opens a new page but cannot be focused with Tab. What is a better starting element?",
    "Use an anchor with a meaningful href for navigation. It supplies familiar link semantics and keyboard behaviour. A button is appropriate when the control performs an in-page action instead.",
    '<main>\n  <h1>Computer science</h1>\n  <nav><a href="notes.html">Notes</a></nav>\n  <article><h2>Binary numbers</h2><p>...</p></article>\n</main>',
    "Create a heading, a notes link and a button that reveals an answer.",
    "Use h1 for the page heading, a with href for the notes destination, and button for revealing content. Give the button an accessible name describing the action.",
    "The alt attribute describes an image’s function or meaning; it is not a place to repeat unrelated keywords.",
    "Which element normally performs an in-page action?",
    ["button", "title", "meta"],
    0,
    "A button is the appropriate interactive control for an action.",
  ),
  T(
    "css-box-model",
    "The CSS box model",
    "Web development",
    "layout",
    "A CSS box has content, padding, border and margin. Padding sits inside the border; margin separates the box from neighbouring layout. The box-sizing property determines whether a declared width refers only to content or includes padding and borders.",
    "Under content-box, add horizontal padding and border widths to the declared content width to obtain the outer border-box width. Under border-box, the declared width already includes those areas. Margins remain outside either box-sizing calculation.",
    "Find the border-box width for width:200px, padding:10px and border:2px under content-box.",
    "The total is 200 + 10 + 10 + 2 + 2 = 224px. With border-box and the same declared width, the border box is 200px, leaving 176px for content. Margins would be additional.",
    ".card { width: 200px; padding: 10px; border: 2px solid; }\n/* content-box outer width = 224px */",
    "Add 8px left and right margins to the content-box example. How much horizontal space is occupied in a simple row?",
    "The border box is 224px; adding both margins gives 240px. This calculation assumes an ordinary horizontal arrangement without other layout effects.",
    "Padding does not create transparent spacing outside the border; that is the role of margin.",
    "What is included in a border-box width?",
    ["Content only", "Content, padding and border", "All margins too"],
    1,
    "border-box includes content, padding and borders but excludes margins.",
  ),
  T(
    "forms-validation",
    "Forms, validation and server checks",
    "Web development",
    "journey-web",
    "A form gathers data through named controls. Labels explain what to enter, and native input types can provide useful validation. Client-side validation improves feedback but cannot establish trust, because a request can be sent without using the page’s form.",
    "The browser gathers control values, serialises them for a request and sends them to a server. The server validates types, lengths, permitted values and authorisation before storing or acting on them. Errors should identify what needs correction without discarding unrelated valid input.",
    "A marks input uses min=0 and max=100. Can the backend assume every request is within that range?",
    "No. A caller can construct a request directly. The backend must enforce the same allowed range and reject values such as −1, 101 or a non-number. The browser constraints remain useful for ordinary users.",
    '<label for="marks">Marks</label>\n<input id="marks" name="marks" type="number" min="0" max="100" required>',
    "List three checks for a teacher chapter title received by an API.",
    "Check that it is a string, trim and enforce sensible length limits, and verify that the caller has permission to edit the chapter. Render the resulting text safely.",
    "Validation and authorisation are different: valid-looking data can still come from an unauthorised caller.",
    "Where must security-relevant validation run?",
    [
      "Only in CSS",
      "On the server as well as helpful browser checks",
      "Only in a placeholder",
    ],
    1,
    "The server must not rely on client-side controls as a security boundary.",
  ),
  T(
    "dom-events",
    "DOM changes and browser events",
    "Web development",
    "journey-web",
    "The Document Object Model represents a page as a tree of objects. An event reports an interaction or other occurrence. Event handlers can update state and change what the browser displays. A displayed change does not automatically mean data was saved on the server.",
    "A learner activates a button, the handler reads or updates application state, and the UI renders the new result. Persistence requires an explicit operation such as local storage or an API request. Accessible controls should support keyboard activation as well as pointer events.",
    "A quiz reveals an explanation when clicked. What are the input, state change and output?",
    "Activation is the input event. A state value such as answerVisible changes from false to true. The explanation appearing on screen is output. If the page refreshes and no persistence was used, the state may return to its initial value.",
    "const [visible, setVisible] = useState(false);\n<button onClick={() => setVisible(true)}>Show explanation</button>",
    "Explain what must be added to preserve a bookmark across page reloads.",
    "Store the bookmark in a suitable persistent location, such as localStorage for one browser or an authenticated backend for cross-device access, then read it when the app starts.",
    "Changing the DOM is not the same as modifying the original HTML file on a server.",
    "What does an event handler do?",
    [
      "Responds to an event",
      "Always writes a database row",
      "Replaces every network protocol",
    ],
    0,
    "A handler responds to an event; its actual effects depend on the code it runs.",
  ),
  T(
    "spreadsheet-references",
    "Relative and absolute spreadsheet references",
    "Productivity",
    "query",
    "A cell reference identifies data used by a formula. Relative references shift when a formula is copied; absolute references keep the specified row and column fixed. Mixed references fix one part. Understanding reference movement is essential when filling a worksheet accurately.",
    "If B2 contains a price and F1 contains a tax rate, =B2*$F$1 uses the row’s price with the same tax rate. Filling down changes B2 to B3 while $F$1 remains fixed. The displayed result and the underlying formula are different views of the same cell.",
    "What does =B2*$F$1 become when copied from C2 to C3?",
    "It becomes =B3*$F$1. The relative price reference moves one row; the absolute tax-rate reference stays in F1. If F1 holds 0.18 and B3 holds 200, the tax is 36.",
    "=B2*$F$1\nCopy down one row:\n=B3*$F$1",
    "Write a formula to add price and tax when B2 holds price and F1 holds rate.",
    "Use =B2*(1+$F$1). If B2=100 and F1=0.18, the total is 118. Check that the rate is stored as 18% or 0.18, not the plain number 18.",
    "The dollar sign fixes a reference; it does not turn the cell into currency.",
    "Which reference fixes both column F and row 1?",
    ["F1", "$F$1", "F$1"],
    1,
    "$F$1 is absolute in both dimensions.",
  ),
  T(
    "spreadsheet-functions",
    "Spreadsheet functions and data checks",
    "Productivity",
    "query",
    "Functions such as SUM, AVERAGE, MIN and MAX summarise ranges. Their results depend on which cells are included and how text, blanks or errors are treated. A formula that calculates successfully can still answer the wrong question if the range is incorrect.",
    "Identify the intended records, select the corresponding range and compare the result with a small hand calculation. For example, =AVERAGE(D2:D4) should not accidentally include a totals row. Separate raw observations from computed summaries.",
    "Three practical scores are 28,25,27. Calculate their total and average.",
    "The total is 80 and the average is 80/3, approximately 26.67. A display rounded to two decimals changes presentation, not necessarily the stored result used by later formulas.",
    "=SUM(D2:D4)\n=AVERAGE(D2:D4)\n=MIN(D2:D4)\n=MAX(D2:D4)",
    "Add a fourth score of 20 and update the average.",
    "The new total is 100 for four observations, so the average is 25. The range must expand to include the new score.",
    "Rounding a displayed cell is not always the same as rounding the underlying calculation with a function.",
    "What is the average of 28,25,27,20?",
    ["20", "25", "100"],
    1,
    "The sum 100 divided by four observations is 25.",
  ),
  T(
    "charts",
    "Choosing charts and reading axes",
    "Productivity",
    null,
    "A chart is a visual argument about data. Bar charts compare categories, line charts commonly show ordered change, and scatter plots show pairs of numeric measurements. The choice of chart, scale, labels and units affects how a reader interprets the evidence.",
    "State the question, identify variable types, choose a suitable chart and label every axis. Check whether a truncated axis exaggerates differences. A chart should preserve access to the underlying values, especially when exact comparison matters.",
    "Which chart would help compare practical marks for four classes?",
    "A bar or column chart is a suitable starting point because the class names are categories and marks are numeric. Use a clearly labeled score axis and an appropriate baseline. A connecting line could misleadingly imply a continuous trend between unrelated categories.",
    "Category: XI-A XI-B XII-A XII-B\nMean mark: 24   27   25    28",
    "Choose a chart for monthly attendance over one academic year.",
    "A line chart can communicate change over ordered months. Label time and attendance units, and distinguish percentages from counts. A table should remain available for exact values.",
    "A visually dramatic chart is not necessarily more truthful. Axes and omitted context can distort interpretation.",
    "What usually suits ordered change over time?",
    ["Line chart", "An unlabeled decorative icon", "A paragraph with no data"],
    0,
    "A line chart can show an ordered time series when its axes and units are clear.",
  ),
  T(
    "documents",
    "Document styles and structured reports",
    "Productivity",
    null,
    "A structured document separates meaning from manual formatting. Styles identify headings, body text and captions consistently. A practical report becomes easier to navigate, update and export when its structure is clear instead of being simulated with repeated spaces and bold text.",
    "Apply heading styles in a logical hierarchy, use real numbered lists for procedures, insert captions for figures and generate a contents list from the headings. Update fields before exporting. Page breaks should express document structure rather than arise from many blank lines.",
    "Why can an automatically generated contents page fail to include a large bold title?",
    "The title may be ordinary text with manual formatting rather than a heading style. Apply the correct heading style and update the contents field. Visual size alone does not establish document structure.",
    "Title\nHeading 1: Aim\nHeading 1: Method\nHeading 2: Test data\nHeading 1: Observations",
    "Organise a practical report with aim, theory, steps, output and conclusion.",
    "Use consistent top-level headings for those sections, a numbered procedure, a captioned output figure and a conclusion linked to the observations. Include source attribution where required.",
    "Pressing Enter many times to start a new page makes layout fragile when earlier text changes.",
    "What should identify a report section?",
    ["A heading style", "Several spaces", "Only a larger font size"],
    0,
    "A heading style records structural meaning and supports navigation and contents generation.",
  ),
  T(
    "presentations",
    "Explaining a concept with slides",
    "Productivity",
    null,
    "A teaching slide should support an explanation rather than compete with it. One clear claim, a relevant diagram and a small example usually communicate more effectively than a dense copied paragraph. Speaker notes can preserve detail that does not need to occupy the screen.",
    "Begin with a question, introduce the model, show a worked example, reveal intermediate steps and finish with a check question. Use readable contrast and captions for media. Any animation should reveal a relationship or sequence that helps understanding.",
    "How would you present binary search in five slides?",
    "Use a sorted array and target, show the first middle comparison, show the retained half, show the next comparison, and explain the stopping condition. Keep the same array positions visually consistent so learners can follow what was eliminated.",
    "Question → Model → Worked trace → Result → Check",
    "Design an explanation slide for a half adder.",
    "Label inputs A and B, show XOR producing Sum and AND producing Carry, then demonstrate the input 11 giving Sum=0 and Carry=1. Include the complete truth table as supporting material.",
    "Animation does not replace an explanation. A moving object without a labeled state change may distract rather than teach.",
    "What is a useful reason to animate an explanation?",
    [
      "To reveal a process step",
      "To hide small text",
      "To make every object move constantly",
    ],
    0,
    "Animation helps when it makes a meaningful change or sequence visible.",
  ),
  T(
    "communication",
    "Clear communication and active listening",
    "Employability skills",
    null,
    "Communication includes a sender, message, medium, receiver and feedback, but successful understanding also depends on context. Active listening means checking meaning rather than merely waiting to speak. In technical work, ambiguity can cause incorrect implementations even when everyone is cooperative.",
    "Use specific descriptions, separate observation from interpretation, and confirm the intended outcome. A useful support message states what was attempted, what was expected, what happened and relevant context. Protect private information while sharing evidence.",
    "Replace “the computer does not work” with a useful classroom support report.",
    "For example: “The login page opens, but submitting my school account displays ‘access denied’. I expected the notes library. The problem began after my role changed.” This narrows the stage and avoids guessing a cause.",
    "Attempt → Expected result → Observed result → Context",
    "Write a clarification for “finish the project soon”.",
    "Ask for the required deliverables, a specific deadline and the criteria for acceptance. Restate the agreed scope so both sides can detect a misunderstanding early.",
    "More words do not automatically mean clearer communication. Relevant details and a shared interpretation matter more.",
    "Which response demonstrates active listening?",
    [
      "Restating the requirement and checking it",
      "Interrupting before the explanation ends",
      "Assuming the cause immediately",
    ],
    0,
    "Restatement and confirmation help establish shared understanding.",
  ),
  T(
    "self-management",
    "Planning work and managing attention",
    "Employability skills",
    null,
    "Self-management turns an intention into a realistic sequence of actions. A useful plan identifies a deliverable, breaks it into tasks, estimates effort and includes time for review. Progress should be assessed against completed work rather than only time spent or visual activity.",
    "Separate urgent deadlines from important preparation. Schedule focused blocks, identify dependencies and review what remains after each block. When an estimate is wrong, update the plan rather than hiding unfinished work. Rest and breaks support sustained attention.",
    "Plan a practical submission due on Friday when coding is incomplete on Monday.",
    "Identify missing programs, complete and test a small batch each day, reserve Thursday for outputs and explanations, and use Friday for final checking and submission. Adjust this schedule to the actual available class time and task size.",
    "Scope → Break down → Schedule → Work → Review → Adjust",
    "Define a measurable goal for tomorrow’s study session.",
    "For example: “Complete two binary-search traces, explain the sorted-input requirement, and check both answers.” This goal produces observable evidence rather than only “study algorithms”.",
    "A long checklist is not a schedule unless tasks have priorities, realistic effort estimates and dependencies.",
    "Which goal is most measurable?",
    [
      "Study more",
      "Become perfect today",
      "Complete and explain two checked traces",
    ],
    2,
    "The last goal states an observable completion criterion.",
  ),
  T(
    "teamwork",
    "Team roles, handovers and feedback",
    "Employability skills",
    null,
    "Teamwork requires shared outcomes, clear responsibilities and visible handovers. Dividing work does not remove the need to integrate it. Constructive feedback describes an observable issue and its effect, then helps the receiver identify a useful next action.",
    "Agree on interfaces and completion criteria before parallel work begins. Keep a shared record of decisions, review changes and test the integrated result. A handover should state what is complete, what remains uncertain and how the next person can continue.",
    "One student builds a login screen and another builds its API. What must they agree on?",
    "They should agree on request fields, endpoint, response shape, authentication behaviour and error messages. Both pieces can work separately yet fail together if those expectations differ.",
    "UI contract ↔ API contract\nIndependent work → Integration → Review",
    "Write constructive feedback for a program that fails when the list is empty.",
    "State: “The program divides by the list length; an empty list causes division by zero. Add an empty-input case and test it.” This addresses behaviour and a repair rather than attacking the author.",
    "Assigning every task to the strongest student may finish one exercise but weakens shared learning and creates a single point of dependency.",
    "What belongs in a useful handover?",
    [
      "Only “done”",
      "Completed work, remaining issues and how to continue",
      "Unrelated personal criticism",
    ],
    1,
    "A handover supports the next action with concrete status and context.",
  ),
  T(
    "entrepreneurship",
    "A problem, a customer and a viable solution",
    "Employability skills",
    null,
    "Entrepreneurship begins with understanding a problem and the people affected by it. A product idea becomes stronger when assumptions about demand, cost and value are tested. Revenue is money earned from sales; profit also accounts for the relevant costs.",
    "Identify the user, investigate the need, propose a small solution, estimate costs, test with feedback and revise. Separate evidence from optimism. A prototype can reveal whether the proposed benefit matters before investing in a complete system.",
    "A printing service charges ₹4 per page and its variable cost is ₹2 per page. What is the contribution from 100 pages before fixed costs?",
    "Revenue is ₹400 and variable cost is ₹200, leaving ₹200 toward fixed costs and profit. It is not automatically ₹200 net profit because rent, equipment and other fixed costs may still apply.",
    "Contribution = Revenue − Variable costs\n100 × (₹4 − ₹2) = ₹200",
    "If fixed costs for the period are ₹150, calculate profit under these assumptions.",
    "Profit is ₹400 − ₹200 − ₹150 = ₹50. State the period and assumptions so costs are not mixed across different time intervals.",
    "Revenue and profit are not interchangeable. High sales can coexist with a loss if total costs are higher.",
    "What is profit in the worked extension?",
    ["₹400", "₹200", "₹50"],
    2,
    "Subtract both variable and stated fixed costs from revenue.",
  ),
  T(
    "green-skills",
    "Sustainable computing and e-waste",
    "Employability skills",
    null,
    "Sustainable computing considers energy, material use, maintenance, reuse and responsible end-of-life handling. A device’s impact includes manufacturing and disposal as well as electricity while it runs. Extending useful life can matter, provided security and reliability remain appropriate.",
    "Measure needs, use suitable power settings, maintain equipment, repair or reuse where practical and send e-waste through appropriate authorised channels. Remove personal data before disposal using a method suitable for the device and sensitivity of its information.",
    "Estimate energy used by a 60 W device operating for five hours.",
    "60 W × 5 h = 300 Wh = 0.3 kWh. This is operating energy for that period, not the device’s entire lifecycle impact. Multiply by the relevant electricity rate if estimating cost.",
    "Energy (kWh) = Power (kW) × Time (h)\n0.060 × 5 = 0.3 kWh",
    "Compare ten 60 W devices running for five hours with ten running for three hours.",
    "The totals are 3 kWh and 1.8 kWh respectively, a difference of 1.2 kWh under the constant-power assumption. Actual consumption may vary with device state.",
    "Deleting a file from a visible folder is not always a sufficient data-sanitisation method before disposal.",
    "Which value is a unit of energy?",
    ["kWh", "W only", "Degrees Celsius"],
    0,
    "A kilowatt-hour measures energy; a watt measures power.",
  ),
  T(
    "digital-citizenship",
    "Privacy, consent and responsible sharing",
    "Society and ethics",
    null,
    "Responsible digital participation includes respecting privacy, seeking consent where appropriate and limiting unnecessary data collection. Public availability does not automatically justify every use of a person’s information. A classroom platform should distinguish public learning material from private student records.",
    "Identify the purpose for collecting data, collect only what is needed, control access and set retention rules. Before sharing a screenshot, inspect it for names, email addresses, passwords and other private information. Consent should be informed and tied to a clear purpose.",
    "A teacher wants to publish a screenshot of a class leaderboard. What should be considered?",
    "Consider whether identifiable student results need to be public, the school’s rules, required consent and a less identifying alternative. A screenshot can reveal more than its central message, including account details at the edges.",
    "Purpose → Minimum data → Appropriate access → Retention → Deletion",
    "Create a safer demonstration dataset for a public lesson.",
    "Use fictional names and invented scores that do not correspond to real students. Label the dataset as an example and avoid importing actual records into a public demonstration.",
    "A blurred name is not always enough if other details can still identify the person.",
    "What is data minimisation?",
    [
      "Collecting every available detail",
      "Collecting only data needed for a stated purpose",
      "Keeping data forever",
    ],
    1,
    "Minimisation limits collection to what is necessary for the purpose.",
  ),
  T(
    "copyright-licensing",
    "Copyright, attribution and software licences",
    "Society and ethics",
    null,
    "Copyright and licensing affect how material may be copied, adapted and shared. Attribution identifies a source but does not by itself grant permission. A licence states conditions under which use is allowed; different licences can impose different requirements on redistribution and modification.",
    "Identify the rights holder and applicable licence, check whether the intended use is permitted, meet conditions such as attribution or sharing terms, and keep a record of the source. Educational use is not a universal exemption from every restriction.",
    "Can a teacher upload any video to a public website merely by writing the creator’s name?",
    "No. Credit is not the same as permission. The teacher must check the applicable licence, permission or legal exception and use an allowed sharing method. Linking to an authorised public video can differ from redistributing a copy.",
    "Source → Licence / permission → Allowed use → Required credit",
    "List information worth recording for a licensed illustration.",
    "Record the title, creator, source URL, licence, access date and any modifications. Include the attribution required by that licence in the appropriate location.",
    "“Free to view” does not necessarily mean “free to redistribute or modify”.",
    "Does attribution alone always permit redistribution?",
    ["Yes", "No", "Only when a filename is changed"],
    1,
    "Permission depends on the licence or another applicable legal basis, not attribution alone.",
  ),
  T(
    "database-keys",
    "Relational keys and integrity",
    "Databases",
    "journey-sql",
    "A relational table represents rows with defined attributes. A candidate key uniquely identifies a row; the chosen primary key is one candidate key. A foreign key links values to a referenced key and helps preserve referential integrity. Meaningful relationships should be expressed explicitly.",
    "Give Student a primary key roll. Another table can refer to Student through that key. A database constraint can reject a referencing value without a matching student, depending on its configuration and operation. A name is often unsuitable as a unique key because names can repeat.",
    "Why is student name alone a risky primary key?",
    "Two students can share a name, and a name can change. A stable assigned identifier avoids confusing identity with a descriptive attribute. The identifier still needs a uniqueness constraint.",
    "Student(roll PRIMARY KEY, name)\nAttendance(roll FOREIGN KEY → Student.roll, date, present)",
    "Explain what should happen when attendance is entered for a nonexistent roll number.",
    "A correctly enforced foreign-key rule should reject the reference or require an intentional workflow to create the related student first. Silently accepting an orphaned record undermines the relationship.",
    "A foreign key need not be unique in its own table: many records can refer to the same parent.",
    "Which rule prevents two students sharing the same primary-key value?",
    ["Uniqueness of the primary key", "A larger font", "Sorting by name"],
    0,
    "A primary key identifies each row uniquely.",
  ),
  T(
    "normalisation",
    "Redundancy and introductory normalisation",
    "Databases",
    "journey-sql",
    "Normalisation organises relational data to reduce certain forms of redundancy and update anomalies. It uses dependencies between attributes, not just visual neatness. A useful first step is to identify what each row represents and which attributes depend on its key.",
    "If a course’s title and instructor are copied into every enrolment row, changing the instructor requires several updates. Separating Course from Enrolment lets enrolments refer to the course identifier. The exact normal form requires checking the relevant dependencies and keys.",
    "An enrolment table repeats course C1’s teacher in twenty rows. What update problem can occur?",
    "Changing only some rows creates contradictory teacher names for the same course. A separate Course record can store the teacher once, while Enrolment records reference C1. This addresses the demonstrated redundancy.",
    "Course(course_id, title, teacher)\nEnrolment(student_id, course_id)",
    "Describe an insertion anomaly in the repeated enrolment design.",
    "If course details can be stored only through an enrolment row, creating a new course before any student enrols becomes awkward or requires a fake enrolment. Separating course data removes that dependency.",
    "Splitting a table arbitrarily does not prove a particular normal form. Identify keys and functional dependencies first.",
    "What is an update anomaly?",
    [
      "Inconsistent copies after a partial update",
      "Any correctly sorted result",
      "A smaller table font",
    ],
    0,
    "Repeated facts can disagree when only some copies are changed.",
  ),
  T(
    "sql-grouping",
    "GROUP BY, aggregates and HAVING",
    "Databases",
    "journey-sql",
    "GROUP BY collects rows with shared grouping values so aggregates can be computed for each group. WHERE filters rows before grouping; HAVING filters grouped results. Confusing these stages can produce an invalid query or a different answer from the intended question.",
    "Filter the source rows, form groups, compute aggregates and apply group conditions. A selected non-aggregate column must be compatible with the grouping rules of the database. Label outputs so a reader knows whether a value is a count, total or average.",
    "Scores are A:80, A:90, B:70. What is the average for each class?",
    "Class A has average 85; class B has average 70. HAVING AVG(marks)>=80 keeps only A. A WHERE marks>=80 filter would remove B’s row before grouping, which is a different operation.",
    "SELECT class, AVG(marks) AS average\nFROM Score GROUP BY class\nHAVING AVG(marks) >= 80;",
    "Add a score B:90 and recalculate the class averages.",
    "A remains 85. B becomes (70+90)/2=80, so both groups satisfy HAVING AVG(marks)>=80.",
    "HAVING is not simply another spelling of WHERE; it can test aggregate properties of groups.",
    "Which clause can filter on COUNT(*) after grouping?",
    ["HAVING", "ORDER BY alone", "A table caption"],
    0,
    "HAVING can apply conditions to grouped aggregate results.",
  ),
  T(
    "transactions",
    "Transactions and all-or-nothing updates",
    "Databases",
    "journey-sql",
    "A transaction groups operations into a logical unit of work. Atomicity means the group succeeds as a unit or is not partly applied; consistency, isolation and durability describe other important transaction properties. Their exact guarantees depend on the database and chosen settings.",
    "Begin the transaction, perform related updates, validate the result and commit if the operation succeeds. Roll back on a failure that should cancel the work. Concurrent transactions also require an appropriate isolation strategy rather than assuming no other client can act.",
    "Why should a money transfer’s debit and credit be treated as one logical operation?",
    "Applying only the debit loses money from the represented accounts; applying only the credit creates an inconsistent result. Atomic handling avoids this partial-update state. A real financial system needs additional validation and controls beyond this teaching example.",
    "BEGIN;\n-- debit one account\n-- credit the other account\nCOMMIT;\n-- ROLLBACK on an error",
    "Explain what rollback should do if the second update fails.",
    "It cancels the uncommitted changes in the transaction so the first update is not left applied alone, under the database’s transaction semantics.",
    "Saving one update successfully is not proof that a multi-step operation is complete.",
    "Which property addresses all-or-nothing application?",
    ["Atomicity", "Font smoothing", "Alphabetical ordering"],
    0,
    "Atomicity is the all-or-nothing property of a transaction.",
  ),
];
